messages:
  no-permission: "&cVous n'avez pas la permission d'utiliser cette commande."
  player-only: "&cCette commande doit être exécutée par un joueur."
  player-not-found: "&cLe joueur '&e%player%&c' n'a pas été trouvé."
  world-created: "&aMonde '&e%world%&a' créé avec succès !"
  world-creation-error: "&cErreur lors de la création du monde '&e%world%&c'."
  world-not-found: "&cLe monde '&e%world%&c' n'existe pas."
  teleported: "&aTéléporté au monde '&e%world%&a'."
  teleported-other: "&aVous avez téléporté '&e%player%&a' au monde '&e%world%&a'."
  usage-tpmonde: "&eUsage: /tpmonde [<Joueur>] <NomMonde>"
  usage-deletemonde: "&eUsage: /deletemonde <NomMonde>"
  world-unload-error: "&cImpossible de décharger le monde '&e%world%&c'."
  world-delete-error: "&cErreur lors de la suppression du monde '&e%world%&c'."
  world-deleted: "&aLe monde '&e%world%&a' a été supprimé avec succès."
  usage-regenmonde: "&eUsage: /regenmonde [monde] <seed>"
  world-regenerated: "&aLe monde '&e%world%&a' a été régénéré avec succès."
  world-regeneration-error: "&cErreur lors de la régénération du monde '&e%world%&c'."
  invalid-seed: "&cLa seed fournie '&e%seed%&c' n'est pas valide."
  random-seed-used: "&aUne seed aléatoire a été utilisée : &e%seed%"
  portal-teleport: "&aVous avez été téléporté vers le monde '&e%target%&a' via un portail."
  usage-linkmonde: "&eUsage: /linkmonde [monde] <nether|end>"
  invalid-type: "&cLe type '&e%type%&c' n'est pas valide. Utilisez '&enethet&c' ou '&eend&c'."
  target-world-not-found: "&cLe monde cible '&e%world%&c' n'existe pas. Créez-le d'abord."
  link-created: "&aLiaison créée : '&e%source%&a' → '&e%target%&a'."